# Generated by Django 3.2.6 on 2021-08-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('detail', models.CharField(max_length=64)),
                ('price', models.SmallIntegerField()),
                ('features', models.TextField(help_text='Displayed in a list, create newline to separate list')),
                ('notes', models.CharField(blank=True, help_text='Displayed highlighted at the end of features list', max_length=128)),
                ('icon', models.CharField(blank=True, help_text='Font awesome 5 class name like so "fas fa-hammer")', max_length=32, null=True)),
            ],
        ),
    ]
