# Generated by Django 3.2.6 on 2021-08-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='razorpay_button',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
    ]
