# Generated by Django 3.2.6 on 2021-08-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_razorpay_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='razorpay_button',
            field=models.TextField(help_text='Razorpay button embed code'),
        ),
    ]
