# Generated by Django 3.2.6 on 2021-11-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_razorpay_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='razorpay_button',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
