# Generated by Django 3.2.6 on 2021-11-22 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_alter_vip_expires'),
        ('store', '0006_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.server'),
        ),
    ]
