# Generated by Django 3.2.6 on 2021-11-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.PositiveSmallIntegerField(default='123'),
            preserve_default=False,
        ),
    ]
