# Generated by Django 3.2.6 on 2021-11-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_alter_vip_expires'),
        ('store', '0010_auto_20211123_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stats.server'),
        ),
    ]
