# Generated by Django 3.2.6 on 2021-11-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20211125_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='token',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.AddField(
            model_name='purchase',
            name='buyer',
            field=models.CharField(max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='receiver',
            field=models.CharField(max_length=54, null=True),
        ),
    ]
