# Generated by Django 3.2.6 on 2023-04-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20230430_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pay_khalti',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pay_stripe',
        ),
        migrations.AddField(
            model_name='product',
            name='payment_method',
            field=models.CharField(choices=[('KHALTI', 'KHALTI'), ('STRIPE', 'STRIPE')], default='KHALTI', max_length=64),
        ),
    ]
