# Generated by Django 3.2.6 on 2023-05-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20230430_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='khaltipurchase',
            name='pidx',
            field=models.CharField(default='asdf', max_length=128),
            preserve_default=False,
        ),
    ]
