# Generated by Django 3.2.6 on 2021-11-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_server_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('steamid', models.CharField(blank=True, max_length=256, null=True)),
                ('steamid64', models.CharField(max_length=128)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('dateofpurchase', models.DateField(auto_now=True)),
                ('expires', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('server', models.PositiveSmallIntegerField(choices=[(1, 'Retake'), (2, 'Deathmatch')], default=1)),
                ('discord_id', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='server',
            name='icon',
        ),
        migrations.AddField(
            model_name='server',
            name='display_name',
            field=models.CharField(default='Server1', max_length=64),
            preserve_default=False,
        ),
    ]
