# Generated by Django 3.2.6 on 2021-11-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20211120_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='profile_url',
            field=models.CharField(default='theonionknight4400', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vip',
            name='steamid64',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
