# Generated by Django 3.2.6 on 2021-11-21 12:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20211121_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='game',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='path_to_vip_file',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_psswd',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='vip',
            name='dateofpurchase',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='vip',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 12, 22)),
        ),
        migrations.AlterField(
            model_name='vip',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.server'),
        ),
    ]
