# Generated by Django 3.2.6 on 2021-11-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20211121_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='game',
        ),
    ]
