# Generated by Django 3.2.6 on 2021-11-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_remove_server_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ssh_ip',
            field=models.CharField(default='123123', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
