# Generated by Django 3.2.6 on 2021-11-23 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_alter_vip_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='slug',
            field=models.SlugField(default='asd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='display_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='vip',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 12, 24)),
        ),
    ]
