# Generated by Django 3.2.6 on 2021-11-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_auto_20211123_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
