# Generated by Django 3.2.6 on 2021-11-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_server_selling_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
