# Generated by Django 3.2.6 on 2021-11-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_alter_server_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
