# Generated by Django 3.2.6 on 2021-11-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_alter_server_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='thumbnail',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
