# Generated by Django 3.2.6 on 2021-11-24 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_alter_server_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 12, 25)),
        ),
    ]
