# Generated by Django 3.2.6 on 2021-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_alter_vip_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='server',
            name='identifier',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='display_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='server',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
