# Generated by Django 3.2.6 on 2021-11-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0020_auto_20211125_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vip',
            options={'ordering': ('expires',)},
        ),
    ]
