# Generated by Django 3.2.6 on 2021-11-26 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0022_auto_20211125_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authtype', models.CharField(max_length=5)),
                ('identity', models.CharField(max_length=65)),
                ('password', models.CharField(blank=True, max_length=65, null=True)),
                ('flags', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=65)),
                ('immunity', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'sm_admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmAdminsGroups',
            fields=[
                ('admin_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('group_id', models.PositiveIntegerField()),
                ('inherit_order', models.IntegerField()),
            ],
            options={
                'db_table': 'sm_admins_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmConfig',
            fields=[
                ('cfg_key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('cfg_value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sm_config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmGroupImmunity',
            fields=[
                ('group_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('other_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'sm_group_immunity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmGroupOverrides',
            fields=[
                ('group_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=32)),
                ('access', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'sm_group_overrides',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flags', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('immunity_level', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'sm_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmOverrides',
            fields=[
                ('type', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('flags', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sm_overrides',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='vip',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 12, 26)),
        ),
    ]
