# Generated by Django 3.2.6 on 2021-11-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_auto_20211126_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='db_identifier',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
