# Generated by Django 3.2.6 on 2021-11-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0024_server_db_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='path_to_vip_file',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_ip',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_port',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_psswd',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_user',
        ),
    ]
