# Generated by Django 3.2.6 on 2021-11-27 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0025_auto_20211126_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='expires',
            field=models.DateField(default=datetime.date(2021, 12, 27)),
        ),
        migrations.AlterField(
            model_name='vip',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='vip',
            name='steamid',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='vip',
            name='steamid64',
            field=models.CharField(max_length=128),
        ),
    ]
