# Generated by Django 3.2.6 on 2023-04-23 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0026_auto_20211127_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='db_hostname',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='server',
            name='db_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='server',
            name='db_pass',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='server',
            name='db_port',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='server',
            name='db_user',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='server',
            name='display_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='vip',
            name='expires',
            field=models.DateField(default=datetime.date(2023, 5, 23)),
        ),
    ]
