# Generated by Django 3.2.6 on 2023-04-24 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0027_auto_20230423_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='db_hostname',
        ),
        migrations.RemoveField(
            model_name='server',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='server',
            name='db_pass',
        ),
        migrations.RemoveField(
            model_name='server',
            name='db_port',
        ),
        migrations.RemoveField(
            model_name='server',
            name='db_user',
        ),
        migrations.AddField(
            model_name='server',
            name='stats_db_url',
            field=models.URLField(blank=True, help_text='will be stored encrypted'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='expires',
            field=models.DateField(default=datetime.date(2023, 5, 24)),
        ),
    ]
