# Generated by Django 3.2.6 on 2023-04-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0028_auto_20230424_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='stats_db_url',
            field=models.CharField(blank=True, help_text=" 'mysql://USER:PASSWORD@HOST:PORT/NAME' , this will be encypted", max_length=1024),
        ),
    ]
