# Generated by Django 3.2.6 on 2023-04-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0029_alter_server_stats_db_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='icon',
            field=models.CharField(default='fas fa-skull-crossbones', max_length=32),
        ),
    ]
