# Generated by Django 3.2.6 on 2023-04-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0030_server_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='server',
            name='port',
        ),
        migrations.AddField(
            model_name='server',
            name='server_hostname',
            field=models.CharField(default='45.76.178.66:27015', help_text='can either be hostname or ip:port', max_length=512),
            preserve_default=False,
        ),
    ]
