# Generated by Django 3.2.6 on 2023-04-30 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0032_remove_server_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='expires',
            field=models.DateField(default=datetime.date(2023, 5, 30)),
        ),
    ]
