# Generated by Django 3.2.6 on 2023-05-01 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0033_alter_vip_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='expires',
            field=models.DateField(default=datetime.date(2023, 5, 31)),
        ),
    ]
