# Generated by Django 3.2.6 on 2023-05-01 12:42

from django.db import migrations, models
import stats.models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0034_alter_vip_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='expires',
            field=models.DateField(default=stats.models.get_expiry),
        ),
    ]
