# Generated by Django 3.2.6 on 2023-05-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0035_alter_vip_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.server'),
        ),
    ]
