# Generated by Django 3.2.6 on 2021-08-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('steamid', models.CharField(db_collation='utf8_unicode_ci', max_length=22, primary_key=True, serialize=False)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
