# Generated by Django 3.2.6 on 2021-08-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0004_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.TextField(blank=True, db_collation='utf8_unicode_ci', null=True),
        ),
    ]
