# Generated by Django 3.2.6 on 2021-09-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0007_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='steamid',
            field=models.CharField(max_length=22, primary_key=True, serialize=False),
        ),
    ]
