# Generated by Django 3.2.6 on 2021-11-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0009_rename_steamid_profile_steamid64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='steamid64',
            field=models.CharField(max_length=17, primary_key=True, serialize=False),
        ),
    ]
