# Generated by Django 3.2.6 on 2021-11-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0010_alter_profile_steamid64'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
