# Generated by Django 3.2.6 on 2021-11-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0011_profile_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
